-- MySQL Script generated by MySQL Workbench
-- Sat 31 Dec 2022 06:33:20 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oficina
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema oficina
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oficina` DEFAULT CHARACTER SET utf8 ;
USE `oficina` ;

-- -----------------------------------------------------
-- Table `oficina`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`Cliente` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `tipo` ENUM('pessoa_fisica', 'pessoa_juridica') NULL,
  `identificacao` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`Veiculo` (
  `id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  `renavam` VARCHAR(45) NULL,
  `placa` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `cliente_id`),
  INDEX `fk_Veiculo_Cliente_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_Veiculo_Cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `oficina`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`Equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`Equipe` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`Ordem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`Ordem` (
  `id` INT NOT NULL,
  `equipe_id` INT NOT NULL,
  `numero` INT NULL,
  `valor` DECIMAL(15,2) NULL,
  `status` VARCHAR(45) NULL,
  `emissao` DATE NULL,
  `conclusao` DATE NULL,
  PRIMARY KEY (`id`, `equipe_id`),
  INDEX `fk_Ordem_Equipe1_idx` (`equipe_id` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem_Equipe1`
    FOREIGN KEY (`equipe_id`)
    REFERENCES `oficina`.`Equipe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`Especialidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`Especialidade` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`Mecanico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`Mecanico` (
  `id` INT NOT NULL,
  `equipe_id` INT NOT NULL,
  `especialidade_id` INT NOT NULL,
  `codigo` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `equipe_id`, `especialidade_id`),
  INDEX `fk_Mecanico_Equipe1_idx` (`equipe_id` ASC) VISIBLE,
  INDEX `fk_Mecanico_Especialidade1_idx` (`especialidade_id` ASC) VISIBLE,
  CONSTRAINT `fk_Mecanico_Equipe1`
    FOREIGN KEY (`equipe_id`)
    REFERENCES `oficina`.`Equipe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mecanico_Especialidade1`
    FOREIGN KEY (`especialidade_id`)
    REFERENCES `oficina`.`Especialidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`Servico` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  `valor` DECIMAL(15,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`Peca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`Peca` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  `valor` DECIMAL(15,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`Ordem_Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`Ordem_Veiculo` (
  `ordem_id` INT NOT NULL,
  `veiculo_id` INT NOT NULL,
  `servico_id` INT NOT NULL,
  `peca_id` INT NOT NULL,
  PRIMARY KEY (`ordem_id`, `veiculo_id`, `servico_id`, `peca_id`),
  INDEX `fk_Ordem_has_Veiculo_Veiculo1_idx` (`veiculo_id` ASC) VISIBLE,
  INDEX `fk_Ordem_has_Veiculo_Ordem1_idx` (`ordem_id` ASC) VISIBLE,
  INDEX `fk_Ordem_Veiculo_Servico1_idx` (`servico_id` ASC) VISIBLE,
  INDEX `fk_Ordem_Veiculo_Custo1_idx` (`peca_id` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem_has_Veiculo_Ordem1`
    FOREIGN KEY (`ordem_id`)
    REFERENCES `oficina`.`Ordem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem_has_Veiculo_Veiculo1`
    FOREIGN KEY (`veiculo_id`)
    REFERENCES `oficina`.`Veiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem_Veiculo_Servico1`
    FOREIGN KEY (`servico_id`)
    REFERENCES `oficina`.`Servico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem_Veiculo_Custo1`
    FOREIGN KEY (`peca_id`)
    REFERENCES `oficina`.`Peca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
